### ISSUE TITLE
Major refactoring 1.0.0

### ISSUE THREAD

**Issue by sepo-one** [sepo27/redux-di#15]
## Start clean
- [x] TypeScript
- [x] eslint
- [x] jest
- [x] precommit hook
- [x] compile

## Rewrite in TypeScript
- [x] `initReducer()`
- [x] `diReducer`
- [x] `diMemoReducer`
- [ ] `combineReducers`

## Update docs
- [ ] update readme
- [ ] update changelog
- [ ] prepare for publish; make sure it's shallow
- [ ] publish v `1.0.0`

**Comment by sepo-one** [comment]
- [ ] rename: `combineDiReducers` -> `combineRootReducers`
- [ ] implement `combineReducers`
- [ ] update readme
- [ ] publish v `0.6.0`
  - [ ] update changelog

**Comment by sepo-one** [comment]
Working example:

```javascript
export const whatsNewReducer = actionMapReducer(WhatsNewInitialState, {
    [APP_MOUNT]: (state: WhatsNewState) => ({
        ...state,
        list: [...WhatsNewList].sort((a: WhatsNewItem, b: WhatsNewItem) => (
            new Date(a.releaseDate).getTime() > new Date(b.releaseDate).getTime()
                ? -1
                : 1
        )),
    }),
    [SET_DEFAULT_PREFERENCES_ACTION]: (state, action) => {
        const
            latestTimestamp = new Date(WHATS_NEW_RELEASE_DATE).getTime(),
            count = defineCount(latestTimestamp, state.list);

        return { ...state, latestTimestamp, count };
    },
    [ANY_ACTION]: diSelReducer(
        { prefLastSeenTimestamp: '@preferences.whatsNewLastSeenTimestamp' },
        (state, _, deps) => {
            if (deps.stale) return state;
            
            return {
                ...state,
                [Lit.latestTimestamp]: deps.prefLastSeenTimestamp,
                [Lit.count]: defineCount(deps.prefLastSeenTimestamp, state[Lit.list]),
            };
        },
    ),
});
```

**Comment by sepo-one** [comment]
Consider `combineReducers()` to be used in root and other deep levels.
Do a POC in: `15-refactor-1.0.0-combine-reducers-poc`.
If POC is satisfactory, update description of this issue.

**Comment by sepo27** [comment]
## Roadmap
- [x] diReducer
  - [x] check for empty dependency map
  - [x] update empty dependencies error message
- [x] refactor di selector
  - [x] remove `DiPathSelector`
  - ~~implement `DiSelector.fromString()`~~
  - [x] implement props: `isAbsolute`, `isRelative`, etc
  - [x] implement generic `DependencyMap<Selector>`
  - [x] incoming dependency map should be: `DependencyMap<string | DiSelector>`
  - [x] stored dependency map should be: `DependencyMap<DiSelector>`
- [x] ensure `combineReducers` returns plain reducer when no absolute paths
- [x] ensure `combineReducers` returns `diReducer` when some absolute paths
- [x] ensure `combineReducers` resolves absolute paths properly for nested reducers
- [ ] more tests for `combineReducers` nested cases
- [ ] `combineReducers` for root
- [ ] resolve todos
